// @vitest-environment node
// Covers the nimbalyst-wiki plugin's build script and its Stop-hook nudge.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { applyRemoteBranch, checkGenerated, rewriteToolNames, writeGenerated } from '../build-wiki-plugin.mjs';

const NUDGE = fileURLToPath(new URL('../../plugins/nimbalyst-wiki/scripts/keeper-nudge.mjs', import.meta.url));

function tempRoot(t) {
  const root = mkdtempSync(path.join(tmpdir(), 'wiki-plugin-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  return root;
}

function fixtureSource(root) {
  const source = path.join(root, 'source');
  for (const skill of ['knowledge-graph', 'knowledge-setup']) {
    mkdirSync(path.join(source, skill, 'references'), { recursive: true });
    writeFileSync(
      path.join(source, skill, 'SKILL.md'),
      `---\nname: ${skill}\ndescription: test\n---\n\n# ${skill}\n\nCall \`tracker_list_types\`, then \`mcp__nimbalyst-trackers__tracker_create\`, then \`tracker_list\`.\n`,
    );
    writeFileSync(path.join(source, skill, 'references', 'kind.yaml'), '# not supported by tracker_define_type\nid: kind\n');
  }
  return source;
}

test('generator renames tracker tools to wiki tools and marks files as generated', (t) => {
  const root = tempRoot(t);
  const sourceDir = fixtureSource(root);
  const targetDir = path.join(root, 'target');

  writeGenerated({ sourceDir, targetDir });
  const skill = readFileSync(path.join(targetDir, 'knowledge-graph', 'SKILL.md'), 'utf8');
  assert.match(skill, /^---\nname: knowledge-graph\n/);
  assert.match(skill, /<!-- GENERATED by scripts\/build-wiki-plugin\.mjs/);
  assert.match(skill, /Every `wiki_\*` call takes `repo`/);
  assert.match(skill, /Call `wiki_list_types`, then `wiki_create_item`, then `wiki_list`\./);
  assert.doesNotMatch(skill, /tracker_|mcp__nimbalyst-trackers__/);
  // Contract: every write carries a changeset; there is no changeset-less path.
  assert.match(skill, /Every write .* requires a `changesetId` from `wiki_begin_changeset`/);
  assert.doesNotMatch(skill, /when one is open/);
  const yaml = readFileSync(path.join(targetDir, 'knowledge-graph', 'references', 'kind.yaml'), 'utf8');
  assert.match(yaml, /^# GENERATED .*\n# not supported by wiki_define_type\n/);
});

test('generator refuses a tracker tool the contract does not map', () => {
  assert.throws(() => rewriteToolNames('use `tracker_link_session`', 'x.md'), /no wiki_\* mapping for tracker_link_session/);
});

test('generator drops desktop-only passages and unwraps remote-only ones', () => {
  const source = [
    'Intro.',
    '',
    '<!-- desktop-only -->',
    'Decide `sharing`; drafts need publishing.',
    '<!-- /desktop-only -->',
    '<!-- remote-only',
    'The server owns sharing.',
    '-->',
    '',
    'Outro.',
    '',
  ].join('\n');
  assert.equal(applyRemoteBranch(source, 'x.md'), 'Intro.\n\nThe server owns sharing.\n\nOutro.\n');
  assert.throws(() => applyRemoteBranch('<!-- desktop-only -->\nno end\n', 'x.md'), /unbalanced/);
  // Files without markers pass through byte for byte, blank lines included.
  assert.equal(applyRemoteBranch('a\n\n\n\nb\n'), 'a\n\n\n\nb\n');
});

test('committed knowledge-setup skill carries no desktop-only sharing or draft steps', () => {
  const setup = readFileSync(fileURLToPath(new URL('../../plugins/nimbalyst-wiki/skills/knowledge-setup/SKILL.md', import.meta.url)), 'utf8');
  assert.doesNotMatch(setup, /promoteExistingItems|sharing: team|as a draft|(?:desktop|remote)-only/);
  assert.match(setup, /wiki_bind_repo/);
});

test('check mode reports drift in either direction', (t) => {
  const root = tempRoot(t);
  const sourceDir = fixtureSource(root);
  const targetDir = path.join(root, 'target');
  writeGenerated({ sourceDir, targetDir });
  assert.deepEqual(checkGenerated({ sourceDir, targetDir }), []);

  appendFileSync(path.join(sourceDir, 'knowledge-setup', 'SKILL.md'), 'Then call `tracker_get`.\n');
  writeFileSync(path.join(targetDir, 'knowledge-graph', 'references', 'stray.yaml'), 'id: stray\n');
  assert.deepEqual(checkGenerated({ sourceDir, targetDir }).sort(), [
    'changed: knowledge-setup/SKILL.md',
    'extra: knowledge-graph/references/stray.yaml',
  ]);

  writeGenerated({ sourceDir, targetDir });
  assert.deepEqual(checkGenerated({ sourceDir, targetDir }), []);
});

test('committed plugin skills match the knowledge extension source', () => {
  assert.deepEqual(checkGenerated(), []);
});

function toolUse(name, input) {
  return JSON.stringify({ type: 'assistant', message: { content: [{ type: 'tool_use', name, input }] } });
}

function runNudge(root, input, env = {}) {
  const result = spawnSync(process.execPath, [NUDGE], {
    input: typeof input === 'string' ? input : JSON.stringify(input),
    encoding: 'utf8',
    env: { ...process.env, NIMBALYST_WIKI_NUDGE_STATE_DIR: path.join(root, 'state'), NIMBALYST_WIKI_NUDGE_MIN_EDITS: '3', ...env },
  });
  assert.equal(result.status, 0, result.stderr);
  return result.stdout.trim() ? JSON.parse(result.stdout) : null;
}

function transcript(root, name, lines) {
  const file = path.join(root, `${name}.jsonl`);
  writeFileSync(file, `${lines.join('\n')}\n`);
  return file;
}

test('nudge blocks once per session, and only after substantive work', (t) => {
  const root = tempRoot(t);
  const edits = transcript(root, 'edits', [
    toolUse('Read', { file_path: 'a.ts' }),
    ...['a.ts', 'b.ts', 'c.ts'].map((file) => toolUse('Edit', { file_path: file })),
  ]);
  const first = runNudge(root, { session_id: 's1', transcript_path: edits, stop_hook_active: false });
  assert.equal(first.decision, 'block');
  assert.match(first.reason, /3 file edits.*\/nimbalyst-wiki:capture.*"nothing to record"/);
  assert.equal(runNudge(root, { session_id: 's1', transcript_path: edits }), null);

  // The threshold is overridable, and below it nothing happens.
  assert.equal(runNudge(root, { session_id: 's2', transcript_path: edits }, { NIMBALYST_WIKI_NUDGE_MIN_EDITS: '4' }), null);

  const commit = transcript(root, 'commit', ['not json', toolUse('Bash', { command: 'git add x && git commit -m "x"' })]);
  assert.match(runNudge(root, { session_id: 's3', transcript_path: commit }).reason, /1 git commit/);
  const plan = transcript(root, 'plan', [toolUse('Write', { file_path: '/repo/nimbalyst-local/plans/thing.md' })]);
  assert.match(runNudge(root, { session_id: 's4', transcript_path: plan }).reason, /a plan/);

  // Already captured through the plugin: no nudge.
  const captured = transcript(root, 'captured', [
    toolUse('Bash', { command: 'git commit -m x' }),
    toolUse('mcp__plugin_nimbalyst-wiki_nimbalyst-wiki__wiki_update_item', { id: 'X' }),
  ]);
  assert.equal(runNudge(root, { session_id: 's5', transcript_path: captured }), null);
});

test('nudge stays quiet in a directory with no git remote', (t) => {
  const root = tempRoot(t);
  const commit = transcript(root, 'commit', [toolUse('Bash', { command: 'git commit -m x' })]);
  const noRemote = path.join(root, 'no-remote');
  mkdirSync(noRemote);
  spawnSync('git', ['init', '-q'], { cwd: noRemote });
  assert.equal(runNudge(root, { session_id: 'r1', transcript_path: commit, cwd: noRemote }), null);
  assert.equal(runNudge(root, { session_id: 'r2', transcript_path: commit, cwd: path.join(root, 'not-a-repo') }), null);

  const withRemote = path.join(root, 'with-remote');
  mkdirSync(withRemote);
  spawnSync('git', ['init', '-q'], { cwd: withRemote });
  spawnSync('git', ['remote', 'add', 'origin', 'git@github.com:acme/widgets.git'], { cwd: withRemote });
  assert.equal(runNudge(root, { session_id: 'r3', transcript_path: commit, cwd: withRemote }).decision, 'block');
});

test('nudge never blocks when stop_hook_active or on bad input', (t) => {
  const root = tempRoot(t);
  const commit = transcript(root, 'commit', [toolUse('Bash', { command: 'git commit -m x' })]);
  assert.equal(runNudge(root, { session_id: 'a', transcript_path: commit, stop_hook_active: true }), null);
  assert.equal(runNudge(root, '{not json'), null);
  assert.equal(runNudge(root, ''), null);
  assert.equal(runNudge(root, { session_id: 'b', transcript_path: path.join(root, 'missing.jsonl') }), null);
  assert.equal(runNudge(root, { transcript_path: commit }), null);
});

test('nudge keeps its markers in a private per-user state dir, not the shared temp dir', (t) => {
  const root = tempRoot(t);
  const commit = transcript(root, 'commit', [toolUse('Bash', { command: 'git commit -m x' })]);

  const xdg = path.join(root, 'xdg');
  assert.equal(runNudge(root, { session_id: 'x1', transcript_path: commit }, { NIMBALYST_WIKI_NUDGE_STATE_DIR: '', XDG_STATE_HOME: xdg }).decision, 'block');
  const xdgDir = path.join(xdg, 'nimbalyst-wiki');
  assert.ok(existsSync(path.join(xdgDir, 'x1.nudged')));
  if (process.platform !== 'win32') assert.equal(statSync(xdgDir).mode & 0o777, 0o700);

  const home = path.join(root, 'home');
  assert.equal(runNudge(root, { session_id: 'h1', transcript_path: commit }, { NIMBALYST_WIKI_NUDGE_STATE_DIR: '', XDG_STATE_HOME: '', HOME: home }).decision, 'block');
  assert.ok(existsSync(path.join(home, '.claude', 'state', 'nimbalyst-wiki', 'h1.nudged')));
});
